services:
  db:
    image: docker.io/bitnami/postgresql:16
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      POSTGRESQL_USERNAME: bn_moodle
      POSTGRESQL_DATABASE: bitnami_moodle
      POSTGRESQL_PASSWORD: bitnami1
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: bn_moodle
      MOODLE_DATABASE_NAME: bitnami_moodle
      MOODLE_DATABASE_PASSWORD: bitnami1
      MOODLE_SMTP_HOST: mail
      MOODLE_SMTP_PORT: 1025
    volumes:
      - ./localfs/opt/bitnami/php/etc/php.ini:/opt/bitnami/php/etc/php.ini
      - ./localfs/bitnami/moodle:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
      - ${PLUGIN_MOUNT:-tmp:/tmp}
    depends_on:
      - db
    restart: always
  mail:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  tmp:
    driver: local
  postgresql_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
