name: Build

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - run: |
          npm ci
          npm run build
