name: Release

permissions:
  contents: write

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - run: |
          cd vue
          npm ci
          npm run build

      - name: Update changes in GitHub repository
        run: |
          git config --global user.name ${{ github.actor }} 
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git add amd/* -f
          git commit -m '[automated commit] add amd folder'
          git push
